### ISSUE TITLE
有异常java.lang.IllegalStateException: The specified child already has a parent. You must call removeView()

### ISSUE THREAD

**Issue by wenbaoxing123** [leotyndale/EnFloatingView#16]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child&#39;s parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5138)
	at android.view.ViewGroup.addView(ViewGroup.java:4967)
	at android.view.ViewGroup.addView(ViewGroup.java:4904)
	at android.view.ViewGroup.addView(ViewGroup.java:4877)
	at com.imuxuan.floatingview.FloatingView.attach(FloatingView.java:98)
	at com.imuxuan.floatingview.FloatingView.attach(FloatingView.java:81)
	at net.ifengniao.task.frame.base.BaseActivity.onStart(BaseActivity.java:104)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7923)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3337)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by leotyndale** [comment]
v1.6版本已修复

**Comment by thirtyyuan** [comment]
> v1.6版本已修复
``` Java
if (mEnFloatingView.getParent() != null) {
    ((ViewGroup) mEnFloatingView.getParent()).removeView(mEnFloatingView);
}
```
请问是这段代码修复的吗？

**Comment by thirtyyuan** [comment]
> > v1.6版本已修复
> 
> ```java
> if (mEnFloatingView.getParent() != null) {
>     ((ViewGroup) mEnFloatingView.getParent()).removeView(mEnFloatingView);
> }
> ```
> 
> 请问是这段代码修复的吗？

应该没错，我加上后修复了，感谢！
